version: '3'
service:
  web:
    build: .
    ports:
      - "3000:3000"
  postgresDB:
    image: sameersbn/postgresql:10-2
    ports:
    - "5432:5432"
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql
    environment:
    - val1: value
  redisService:
    image: redis:alpine
    ports:
    - 6379:6379
    volumes:
      - /srv/docker/redis:/var/lib/redis